transforms: [sentencepiece, prefix, suffix]
#transforms: [prefix, suffix]
# nllb-200 specific prefixing and suffixing
src_prefix: "fra_Latn"
tgt_prefix: "eng_Latn" 
tgt_file_prefix: false
src_suffix: ""
tgt_suffix: ""

#### Subword
src_subword_model: "../openNMT/flores200_sacrebleu_tokenizer_spm.model"
tgt_subword_model: "../openNMT/flores200_sacrebleu_tokenizer_spm.model"
src_subword_nbest: 1
src_subword_alpha: 0.0
tgt_subword_nbest: 1
tgt_subword_alpha: 0.0
# Model info
model: "nllb-200-1.3B-onmt.pt"
# Inference
max_length: 1024
gpu: 0
batch_type: tokens
batch_size: 1024
beam_size: 5
report_time: true
early_stopping: false
