transforms: [sentencepiece, prefix, suffix]

# Prefixos para NLLB
src_prefix: "</s> fra_Latn"
tgt_prefix: "eng_Latn"
tgt_file_prefix: true

# Sufixos (vazios)
src_suffix: ""
tgt_suffix: ""

# Subword models
src_subword_model: "../openNMT/flores200_sacrebleu_tokenizer_spm.model"
tgt_subword_model: "../openNMT/flores200_sacrebleu_tokenizer_spm.model"

# Modelo
model: "nllb-200-1.3B-onmt.pt"

# Inference
max_length: 512
gpu: 0
batch_type: tokens
batch_size: 2048
beam_size: 5
report_time: true
